version: "3"

services:
  image-oss:
    image: dingdangdog/image-oss:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${PWD}/images:/data/image-oss/images
      - ${PWD}/application.yml:/usr/image-oss/jar/application.yml
    ports:
      - 11080:80