server:
  port: 11033

spring:
  application:
    name: upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

fileType:
  up: bmp,jpg,jpeg,png,tif,gif,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw,WMF,webp,avif,apng
  wm: jpg,jpeg,png

keyList: abc

image:
  url: http://localhost:80/images/
  path: /data/image-oss/images/