version: "3.0"

services:
  image-oss:
    container_name: image-oss
    image: dingdangdog/image-oss:2.0.1
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./images:/app/images
      - ./config.json:/app/config/config.json
    ports:
      - 11080:80
